import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Nav from "@/components/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`text-2xl h-screen w-screen flex flex-col`}>
          <Nav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
